version: '3.8'

services:
    php:
        build: .
        volumes:
            - .:/var/www
        working_dir: /var/www
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
